### ISSUE TITLE
Docker image not having knn.space_type feature

### ISSUE THREAD

**Issue by frizfealer** [opendistro-for-elasticsearch/k-NN#101]
I've pulled  amazon/opendistro-for-elasticsearch:1.6.0, the knn plugin it includes seems not having the index.knn.space_type features

When I use 
PUT /myindex
init_settings={
    "settings": {
        "index": {
            "knn": True,
            "knn.space_type": "cosinesimil"
        }
    },
    "mappings": {
        "properties": {
        "my_vector1": {
            "type": "knn_vector",
            "dimension": 640
        }
        }
    }
}
I got the error: 
'error': {'root_cause': [{'type': 'illegal_argument_exception', 'reason': 'unknown setting [index.knn.space_type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings'}],...

Could you include the version with cosine similarity to the docker image?

Thanks,
Yeu-Chern

**Comment by vamshin** [comment]
Hi @frizfealer ,

We have not build the cosine similarity feature into our docker image. We will be building this functionality soon. Will keep you posted.

**Comment by Jhangsy** [comment]
Hi, I encountered the save error when using cosine similarity.  Is it because the rpm package dose not have ```knn.space_type``` ?

**Comment by vamshin** [comment]
@Jhangsy correct. You should be able to use Cosine similarity with 1.7.0 release.

**Comment by vamshin** [comment]
Hi, we just released 1.7.0 docker image. Cosine similarity should be part of this image.
