### ISSUE TITLE
Dimension value missing for vector

### ISSUE THREAD

**Issue by Jhangsy** [opendistro-for-elasticsearch/k-NN#106]
Hi, I have create a index with knn vector successfully. But when I try to insert doc to es, I got 'Dimension value missing for vector' error.  
Mappings are as follows:
```
{"mappings":{"properties":{"embedding":{"type":"knn_vector","dimension":312},"intention":{"type":"keyword"},"intention_en":{"type":"keyword"},"user_say":{"type":"text","analyzer":"ik_smart"}}}}}
```
Error messages are 
```
elasticsearch.exceptions.RequestError: RequestError(400, u'mapper_parsing_exception', u'Dimension value missing for vector: embedding')
```
The dimension value is in mapping, I got no idea why this happens.

**Comment by Jhangsy** [comment]
I tried examples on readme and got the same error.

**Comment by vamshin** [comment]
@Jhangsy Could you provide complete steps of index creation and sample documents you were indexing?

**Comment by Jhangsy** [comment]
> @Jhangsy Could you provide complete steps of index creation and sample documents you were indexing?

Hi, Thank you for replying. I found it is because of the incompatibility elasticsearch version.
