### ISSUE TITLE
Ability to pass ef_search parameter in the query

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#116]
Currently ef_search is a static setting passed at index creation time. ef_search is something that could be changed per query. This issue is to provide support to mention ef_search in the query along with the ```k```.  If ef_search is not specified in the query, fall back to the index settings. 

Example query would look like

```
"query": {
  "knn": {
   "my_vector": {
     "vector": [3, 4],
     "k": 2,
     "ef_search": 1024
   }        
  }
 }
```

**Comment by chenqi0805** [comment]
TODO:

1. Add `ef_search` into KNNQuery
2. Adapt loadIndex API to receive `ef_search` from query.
3. Add test case in `KNNESIT`
