### ISSUE TITLE
Updrade nmslibrary version from 1.7.3.6 to the latest version

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#128]
Some of the Spaces(dot product) are not available as part of nmslib 1.7.3.6 version. Upgrade current library version to get most of the support in nmslib(make sure they are part of Apache2.0 license)

**Comment by vamshin** [comment]
We should check for version compatibility. We need to ensure backward compatibility. Switching to newer version of nmslib should still support ability to read the indexes created with old version of nmslib.

**Comment by chenqi0805** [comment]
Tried checking out v2.0.6 for the submodule, which does not break the current test suite. Will check backward compatibility.
