### ISSUE TITLE
how install this plugin to elasticsearch?

### ISSUE THREAD

**Issue by rrjia** [opendistro-for-elasticsearch/k-NN#131]
from readme I can not find how to install this plugin to elasticsearch for experiment，in opendistro-for-elasticsearch i also not find this plugin by command "curl -XGET https://localhost:9200/_cat/plugins?v -u admin:admin --insecure", Looking forward to your reply

**Comment by jmazanec15** [comment]
Hi @rrjia, for opendistro-for-elasticsearch, what artifact are you using? Currently, the k-NN plugin is present in the RPM, DEB, and Docker Image, but not in the Tarball. We are planning on adding it in to the Tarball in future releases.

Additionally, at the moment, the k-NN plugin is not supported for standalone plugin installation. The documentation can be found [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#knn).

**Comment by rrjia** [comment]
thanks, i install opendistro-for-elasticsearch by Tarball, is knn-plugin planing support install on public elastic search?

**Comment by rrjia** [comment]
install  opendistro-for-elasticsearch from DEB after thsi commad:

sudo apt install opendistroforelasticsearch

meet error:

dpkg: error processing archive /var/cache/apt/archives/opendistroforelasticsearch_1.8.0-1_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 5

**Comment by jmazanec15** [comment]
> thanks, i install opendistro-for-elasticsearch by Tarball, is knn-plugin planing support install on public elastic search?

Yes, in the future, we are going to add the k-NN plugin into the Tarball. In order to install the zip, you have to ensure that the shared library is added to the library path. Documentation of this can be found [here](https://github.com/opendistro-for-elasticsearch/k-NN#java-native-library-usage).

**Comment by jmazanec15** [comment]
> install opendistro-for-elasticsearch from DEB after thsi commad:
> 
> sudo apt install opendistroforelasticsearch
> 
> meet error:
> 
> dpkg: error processing archive /var/cache/apt/archives/opendistroforelasticsearch_1.8.0-1_amd64.deb (--unpack):
> subprocess new pre-installation script returned error exit status 5

Hmm, this seems strange. Did you follow [these](https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/) steps? If so, could you provide more information on your environment, such as the Operating System you are using?

**Comment by rrjia** [comment]
> > install opendistro-for-elasticsearch from DEB after thsi commad:
> > sudo apt install opendistroforelasticsearch
> > meet error:
> > dpkg: error processing archive /var/cache/apt/archives/opendistroforelasticsearch_1.8.0-1_amd64.deb (--unpack):
> > subprocess new pre-installation script returned error exit status 5
> 
> Hmm, this seems strange. Did you follow [these](https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/) steps? If so, could you provide more information on your environment, such as the Operating System you are using?

yes, i follow all steps on website (https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/)

my Operating System information:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by jmazanec15** [comment]
I am working to reproduce the issue. One question, does your cluster access to the internet? There is a known issue [here](https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/120) where installation fails when the cluster does not have access to internet. In that thread, there is a temporary workaround.

We are working to resolve this problem now by building a separate DEB/RPM for the k-NN library.

**Comment by rrjia** [comment]
thanks for your help, my cluster has accessibility  to the internet, more error information as follow:

--2020-06-08 08:57:52--  https://d3g5vo6xdbdb9a.cloudfront.net/downloads/k-NN-lib/libKNNIndexV1_7_3_6.zip
Resolving d3g5vo6xdbdb9a.cloudfront.net (d3g5vo6xdbdb9a.cloudfront.net)... 13.225.157.30, 13.225.157.214, 13.225.157.193, ...
Connecting to d3g5vo6xdbdb9a.cloudfront.net (d3g5vo6xdbdb9a.cloudfront.net)|13.225.157.30|:443... connected.
ERROR: cannot verify d3g5vo6xdbdb9a.cloudfront.net's certificate, issued by ‘CN=DigiCert Global CA G2,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to d3g5vo6xdbdb9a.cloudfront.net insecurely, use `--no-check-certificate'.

**Comment by jmazanec15** [comment]
This is strange. Using an Ubuntu 16.04 EC2 instance, and following the steps in the link above, I was not able to reproduce the issue. Also, running the command `wget https://d3g5vo6xdbdb9a.cloudfront.net/downloads/k-NN-lib/libKNNIndexV1_7_3_6.zip` works on my machine.

Does your machine have the `ca-certificates` package installed? Can you confirm you are able to access other https URLs?

**Comment by yashi0099** [comment]
Hi 
I am getting below error:
root@yshicoder:/home/yshicoder/Desktop# sudo apt-get install elasticsearch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package elasticsearch
