### ISSUE TITLE
Is there any support for Windows?

### ISSUE THREAD

**Issue by BeardyBear** [opendistro-for-elasticsearch/k-NN#133]
Hi guys,

I have noticed that KNN plugin is not shipped with OpenDistro's windows installer.
Are there any plans to include it in the future?

..and if not, what is the reason we cannot run it on windows?

Thank you!

**Comment by vamshin** [comment]
hi @BeardyBear ,

Yes we have plans to include in the [future](https://github.com/opendistro-for-elasticsearch/k-NN/issues/57) . We could not prioritize as we did not see requests for windows support from ODFE community.

**Comment by BeardyBear** [comment]
hi @vamshin 

We are considering to help you out with this. How much work is that?
If this is a project we could complete in a reasonable time then we'd be more than happy to contribute.
Can we chat somewhere about it?

**Comment by BeardyBear** [comment]
Okay, with a few changes to the codebase I've made it work on Windows.

**Comment by vamshin** [comment]
Hi @BeardyBear,

Would you be able to provide steps you followed to make library work for windows. This will be helpful for community trying to use this plugin for windows.

**Comment by BeardyBear** [comment]
Here are the steps for building the KNN lib and plugin on Windows:

1) Edit `jni/CMakeLists`:

Switch from this:

```bash
if (${CMAKE_SYSTEM_NAME} STREQUAL Darwin)
    set(CMAKE_MACOSX_RPATH 1)
    set(JVM_OS_TYPE darwin)
    set(LIB_EXT .jnilib)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL Linux)
    set(JVM_OS_TYPE linux)
    set(LIB_EXT .so)
else()
    message( FATAL_ERROR "Unable to run on system: ${CMAKE_SYSTEM_NAME}")
endif()
```
… to this:

```bash
if (${CMAKE_SYSTEM_NAME} STREQUAL Darwin)
    set(CMAKE_MACOSX_RPATH 1)
    set(JVM_OS_TYPE darwin)
    set(LIB_EXT .jnilib)
elseif(${CMAKE_SYSTEM_NAME} STREQUAL Linux)
    set(JVM_OS_TYPE linux)
    set(LIB_EXT .so)
else()
    set(JVM_OS_TYPE windows)
    set(LIB_EXT .dll)
endif()
```
2) Run `cmake .` at jni folder.
3) Edit `com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex.cpp`:
At line 96, switch `int* object_ids = NULL;` to `jint* object_ids = NULL;`

4) Open jni folder with Visual Studio. Switch build mode to “Release”. Build solution.
5) Copy contents of `jni/Release` to "C:\Windows\System32". The folder should contain following files:
    - KNNIndexV1_7_3_6.dll
    - KNNIndexV1_7_3_6.exp
    - KNNIndexV1_7_3_6.lib
    - NonMetricSpaceLib.lib

6) Edit `build.gradle` file. Comment out `cmakeJniLib` task at line 140, comment out `buildJniLib` task at line 145. In `makeJniLib task`, comment out line 152.
7) Run `./gradlew release` from root folder
8) You will find a plugin in `builds/plugins` folder, move it to ES’ plugin location

So far my benchmarks show close to identical behavior compared to Linux.
Enjoy.

I've made a fork for my personal convenience: https://github.com/BeardyBear/k-NN
Steps 2, 4, 5 and 7 are still required if you decide to pull it.

**Comment by BeardyBear** [comment]
I've made a fork for my personal convenience: https://github.com/BeardyBear/k-NN

Steps 2, 4, 5 and 7 are still required if you decide to pull it.
