### ISSUE TITLE
versioning opendistro nmslib zip artifact

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#140]
As of today we seem to override the .so zip file in the bucket for each release. This could potentially break the older versions which still refer this bucket. This creates compatibility issues

Zip file referred here : https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/elasticsearch/linux_distributions/scripts/preInstall.sh

**Comment by jmazanec15** [comment]
This issue will be fixed in 1.9.0 release. However, we need to address how it will be fixed for 1.8, 1.7, 1.6.
