### ISSUE TITLE
Reranking results with multiple vectors

### ISSUE THREAD

**Issue by naveenkumarmarri** [opendistro-for-elasticsearch/k-NN#142]
I've created an index with two vectors with the following schema

```
ID, feature_vector1, feature_vector2
```

Here `feature_vector1` is list of 500 floats and `feature_vector2` is list of 100 floats
I want to have the following. 

- perform search on the entire index using `feature_vector1`
- using the results of the search, I want to perform reranking of the results based on the similarity with `feature_vector2` for the corresponding `ID`

I was able to perform KNN on `feature_vector1`. 
But not sure how to apply `post_filter` on top the result obtained on `feature_vector1`. Is there a way to achieve this.

@vamshin

**Comment by vamshin** [comment]
Hi @naveenkumarmarri ,

Please raise questions related to k-NN plugin  here https://discuss.opendistrocommunity.dev/c/k-NN/ . we will track bugs/feature/enhancement in this section. we will get back to this question soon

**Comment by naveenkumarmarri** [comment]
@vamshin @sean-zheng-amazon 
I tried to add issue on the forum. But the account is on hold for 4 days. I'm wondering if you can help me out here as we are in time crunch.
I tried adding knn query in `post_filter`. But looks like that is not supported

```
query = {
                "knn": {
                    "embeddings": {
                        "vector": embedding,
                        "k": k
                    }
                }
        }
        post_filter = {
            "post_filter": {
                "query": {
                    "knn": {
                        "text_embeddings": {
                            "vector": text_embedding,
                            "k": k
                        }
                    }
                }
                }
        }
        result = self.es.search(body={"_source": ["_id", "_score"],"query": query, "post_filter": post_filter}, index=index)
        
```

Is there a way to achieve this?

**Comment by vamshin** [comment]
Followed up here https://discuss.opendistrocommunity.dev/t/reranking-results-with-multiple-vectors/3140
