### ISSUE TITLE
Different results for Nmslib and Elastic Knn Search

### ISSUE THREAD

**Issue by pawanm09** [opendistro-for-elasticsearch/k-NN#144]
Thanks for the Library

I created a Nmslib Index of 200,000 Vectors and created an Elasticsearch Knn Index using the same vectors with the same properties.

Then I searched for 50 similar results of the first 10,000 vectors in both Indices and compared the results. 

On average, only 0.5% of the results matched. 

Since elasticsearch-knn is based on NMSLIB, so I think results should also match.

**Comment by vamshin** [comment]
Hi @nmsaey42,

Please raise questions related to k-NN plugin here https://discuss.opendistrocommunity.dev/c/k-NN/ . we will track bugs/feature/enhancement in github. we will get back to this question soon. Thanks

**Comment by pawanm09** [comment]
@vamshin  
I am unable to create a topic on the forum.

**Comment by vamshin** [comment]
@nmsaey42 sorry about that. Do you see any error?

**Comment by jmazanec15** [comment]
Issue related to #154 . Closing
