### ISSUE TITLE
Opendistro 1.9 crashes for certain instance types RPM/DEB/TAR

### ISSUE THREAD

**Issue by jmazanec15** [opendistro-for-elasticsearch/k-NN#163]
# Overview
There is a bug for k-NN binary library for ODFE 1.9 for RPM/TAR/DEB artifacts. The library crashes ES on specific machines. For instance, ODFE 1.9 does not crash on m5 and c5 AWS instance types work, however, ODFE 1.9 crashes on m4 instance types.

This is may be due to the environment in which the binary library we distribute is compiled. Currently, we build the library using Github Actions runners. It is possible the binary is compiled to use optimized instructions available on the machine the Github runner uses, which is not available on certain instance types. The binary that we distribute should not contain optimized instructions in order to maximize compatibility.

# Repro Steps
1. Launch AWS EC2 instance with type m4.xlarge
2. Following this link to install and start RPM or TAR or DEB: https://opendistro.github.io/for-elasticsearch-docs/docs/install/rpm/
3. Run the following commands:
```
curl -X PUT "https://localhost:9200/myindex" -u admin:admin --insecure -H 'Content-Type: application/json' -d'
{
  "settings" : {
    "number_of_shards" :   1,
    "number_of_replicas" : 0,
    "index": {
        "knn": true,
    }
  },
  "mappings": {
      "properties": {
        "my_vector": {
          "type": "knn_vector",
          "dimension": 2
        }
      }
  }
}
'
 
curl -X POST "https://localhost:9200/_bulk" -u admin:admin --insecure -H 'Content-Type: application/json' -d'
{ "create" : { "_index" : "myindex", "_id": "6" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "3" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "4" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "5" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "6" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "7" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "8" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "9" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "a" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "b" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "c" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "d" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "e" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "f" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "g" } } } }
{ "my_vector" : [1.5, 2.5]}
{ "create" : { "_index" : "myindex", "_id": "h" } } } }
{ "my_vector" : [1.5, 2.5]}

curl "https://localhost:9200/myindex/_flush" -u admin:admin --insecure

# The following message will be produced
curl: (7) Failed to connect to localhost port 9200: Connection refused
```

# Work around
Currently, the best work around is to build/install the artifact from source following these steps:
```
git clone https://github.com/opendistro-for-elasticsearch/k-NN.git
cd k-NN
git checkout opendistro-1.9
cd jni
cmake .
make package

# The artifacts will be in this location: k-NN/jni/packages
```

**Comment by vamshin** [comment]
Hi @jmazanec15,

Is it possible to turn off optimization during compilation?

**Comment by jmazanec15** [comment]
Hi @vamshin, 

Passing the `-march=x86-64` flag during compilation should turn off optimization.

Unfortunately, when running `cmake` to build the library, it does not look like we can override setting of `CMAKE_CXX_FLAGS_RELEASE` in [v1736](https://github.com/nmslib/nmslib/blob/v1.7.3.6/similarity_search/CMakeLists.txt#L48) or `SIMD_FLAGS` in [v206](https://github.com/nmslib/nmslib/blob/v2.0.6/similarity_search/CMakeLists.txt#L38) with the cmake `-D` flag to change `-march=native` flag to `-march=x86-64`. I believe it is because they are normal variables as opposed to cached variables in CMake.

As a workaround, we could manually edit the CMakeLists file of NMSLIB from the Github Action that builds our library with a sed command in order to change `-march=native` to `-march=x86-64`. For example:
```
git submodule update --init -- jni/external/nmslib
sed -i 's/-march=native/-march=x86-64/g' external/nmslib/similarity_search/CMakeLists.txt
cmake .
make package
```

I am open to other suggestions.

**Comment by jmazanec15** [comment]
To install from source on Amazon Linux 2 with RPM:
```
sudo yum install gcc-c++ cmake git rpm-build -y
export JAVA_HOME=/usr/share/elasticsearch/jdk
git clone https://github.com/opendistro-for-elasticsearch/k-NN.git
cd k-NN
git fetch
git checkout opendistro-1.9
cd jni
cmake .
make package

sudo yum remove opendistro-knnlib -y
sudo yum localinstall packages/opendistro-knnlib-1.9.0.0-0.1_linux.x86_64.rpm -y
sudo yum install opendistro-knn -y

```

To install from source on Ubuntu with DEB:
```
sudo apt install cmake g++ git rpm -y
export JAVA_HOME=/usr/share/elasticsearch/jdk
git clone https://github.com/opendistro-for-elasticsearch/k-NN.git
cd k-NN
git fetch
git checkout opendistro-1.9
cd jni
cmake .
make package

sudo apt remove opendistro-knnlib -y
sudo dpkg -i packages/opendistro-knnlib-1.9.0.0-0.1_linux.x86_64.deb
sudo apt install opendistro-knn -y
```
