### ISSUE TITLE
Better scoring function in KNN weight

### ISSUE THREAD

**Issue by chenqi0805** [opendistro-for-elasticsearch/k-NN#171]
Splits from #161 . Our current inverting score function 

https://github.com/opendistro-for-elasticsearch/k-NN/blob/d12cee574428c4b74537916ca3fa5a5cbdcd206c/src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNWeight.java#L113

does not cover raw nmslib knn similarity search score ranging from - maxfloat to + maxfloat. e.g. negative dot product value will not be inverted properly and even introduces singularity at 1. We should replace it with a scoring function that overs the whole real axis and inverts the raw similarity search score accordingly. 

My proposal is to use 1-sigmoid(result.getScore()) = 1 / (1 + exp(result.getScore())). If we want to keep maximum score at 1 for positive raw scores, we can multiply by factor of 2. Comments and suggestions are welcome.

**Comment by jmazanec15** [comment]
Hi @chenqi0805, interesting idea. I have a couple questions about Sigmoid function:

1. What happens when the distance returned by nmslib is high (i.e. 10,000)? Wouldn't this lead to an overflow?

2. What are the performance implications of this approach?

Additionally, another function we could look into for scoring is:
```
x/sqrt(1 + x^2) + 1
```

which would map all distances from 0 to 2.

**Comment by chenqi0805** [comment]
Hi, @jmazanec15 , thx for pointing out the issues.

> 1. What happens when the distance returned by nmslib is high (i.e. 10,000)? Wouldn't this lead to an overflow?

I experimented and found that for x~1000, exp(x) goes to inf and exp(-x) goes to zero. So the asymptotic behavior of sigmoid is not ideal for machine precision.

> 2. What are the performance implications of this approach?
> Additionally, another function we could look into for scoring is:

> x/sqrt(1 + x^2) + 1
> which would map all distances from 0 to 2.

I doubt the time complexity is O(log x) for exponentiation. But I like your proposal except that it should be `-x/sqrt(1 + x^2) + 1` for inverting the score. Here are some benchmarks

```
class Scratch {
  public static double func(double x) {
    return -x/Math.sqrt(1 + x*x) + 1;
  }
    public static void main(String[] args) {
        double x = -100;
        System.out.println(func(x));

        x = -1000;
        System.out.println(func(x));

        x = -10000;
        System.out.println(func(x));

      x = -50000;
      System.out.println(func(x));

      x = -100000;
      System.out.println(func(x));

      x = -500000;
      System.out.println(func(x));

      x = -1000000;
      System.out.println(func(x));

      x = -1500000;
      System.out.println(func(x));

      x = -2000000;
      System.out.println(func(x));

      x = -2500000;
      System.out.println(func(x));
    }
}
```
yields
```
1.9999500037496876
1.999999500000375
1.999999995
1.9999999998
1.99999999995
1.9999999999979998
1.9999999999995
1.9999999999997777
1.999999999999875
1.99999999999992
```
but then we will lose the precision on converting the score into **float** which is required by lucene scorer.
```
1.99995
1.9999995
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
```

**Comment by chenqi0805** [comment]
I think another option is to use **piecewise** scoring function

score(x) = 1/(1+x) if x>=0 else 2+1/(x-1)

which preserves the current precision, does not change the performance and inverts the scores for ranking.

**Comment by jmazanec15** [comment]
That is a good idea. So, the more negative the score is, the "nearer" it is to the query. 

So: 
```
   x -> -inf, score -> 2
   x -> 0, score   -> 1
   x -> inf, score -> 0
```

That makes sense to me. Nothing would change for cosine similarity and l2, while we would be able to add support for negative dot product.

**Comment by vamshin** [comment]
Seems like a plan. LGTM as well.
