### ISSUE TITLE
KNNESSettingsTestIT failure in action "Build and Test k-NN Plugin"

### ISSUE THREAD

**Issue by jmazanec15** [opendistro-for-elasticsearch/k-NN#178]
KNNESSettingsTestIT fails on Ubuntu during [Github action](https://github.com/opendistro-for-elasticsearch/k-NN/runs/899654200?check_suite_focus=true). Additionally, was able to repro on Ubuntu 16:
```
com.amazon.opendistroforelasticsearch.knn.index.KNNESSettingsTestIT > testCacheRebuiltAfterUpdateIndexSettings FAILED
    java.lang.AssertionError: expected:<1> but was:<4>
        at __randomizedtesting.SeedInfo.seed([C11B19DAD31088ED:8E515F7F7E6EEC35]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.amazon.opendistroforelasticsearch.knn.index.KNNESSettingsTestIT.testCacheRebuiltAfterUpdateIndexSettings(KNNESSettingsTestIT.java:130)
```

The code that was being checked in was #170 , however, this does not impact any testing logic or that action logic. So, this is most likely a flaky test. I think it may be related to the tests in #162, even though the action for that PR [did not fail](https://github.com/opendistro-for-elasticsearch/k-NN/actions/runs/177579646).

**Comment by jmazanec15** [comment]
So, I think the issue is that the indices from another test are deleted, but not cleared from the cache, before the next test begins.

Indices for rest test cases are deleted after a test [here](https://github.com/elastic/elasticsearch/blob/dd67392b66384e1dda3c8ac77c6263cd1cc204dc/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java#L308)

**Comment by jmazanec15** [comment]
For this, the cache should be cleared before the next test case starts. We can implement this by adding on to `cleanUpCluster`. When we have the clear cache API, we should use that to accomplish this. However, until then, we will need to use a workaround. One way to do this is to bounce one k-NN setting. This will result in an empty cache. @vamshin does this sound good?

**Comment by vamshin** [comment]
@jmazanec15 LGTM! 
Lets leave a TODO comment on the test case and tag the issue to track the fix with clear cache api.

**Comment by jmazanec15** [comment]
Added comment here: https://github.com/opendistro-for-elasticsearch/k-NN/issues/68#issuecomment-665142635
