### ISSUE TITLE
Question: How do I integrate knn plugin to my existing Elastic Search OSS? 

### ISSUE THREAD

**Issue by mtikmani** [opendistro-for-elasticsearch/k-NN#180]
I am already using an existing elastic search OSS distribution for our document similarity usage. I want to use knn plugin  to my existing ES OSS deployment.  I am ok to build knn feature from source and attach it to my ES OSS, if that is needed.

Is it possible to do that?

**Comment by vamshin** [comment]
Hi @mtikmani,

Yes definitely possible. Assuming your Elasticsearch version is 7.8.

1. You need to build zip distribution of the plugin first.

-> check out k-NN package and branch opendistro-1.9 
-> ./gradlew build
You would notice opendistro-knn-1.9.0.0.zip in build/distributions/ folder.
-> create a folder ```opendistro-knn``` in ```plugins``` folder under ES dir and unzip the contents of ```opendistro-knn-1.9.0.0.zip```  in this folder.

 2. Add library to the java path
You would notice ```libKNNIndexV1_7_3_6.so``` file in folder ```jni/release```. Set the absolute path to this library in the ```jvm.options``` file. Add ```-Djava.library.path=<path_to_lib_file> ```  to the ```jvm.options``` file to make the library discoverable to Elasticsearch's JVM. 
Example :- -Djava.library.path=/tmp/k-NN/jni/release/
 
3. Restart ES process.

4. check ```opendistro-knn``` is visible in  ```_cat/plugins```

5. Do same basic indexing/search to validate the library is loaded correctly

**Comment by mtikmani** [comment]
Thanks @vamshin : I will try it out.  Can I use ES OSS 7.6 instead of OSS 7.8 or does it have to be OSS 7.8 only?

**Comment by toko-stephen-leo** [comment]
Hi I'm trying to install on ES version 7.9 by following the steps mentioned by @vamshin but I'm running into the following issue during the build. Pls help suggest what I can do to work around this?
Pls let me know if further information is required.

```
Tests with failures:
 - com.amazon.opendistroforelasticsearch.knn.index.KNNIndexShardTests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.index.KNNVectorFieldMapperTests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.plugin.stats.suppliers.KNNCounterSupplierTests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.index.codec.KNN86Codec.KNN86CodecTests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.plugin.scripts.KNNScoringUtilTests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.index.KNNQueryBuilderTests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.common.exception.KNNInvalidIndicesExceptionTests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.index.KNNIndexCacheTests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.index.KNNJNITests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.plugin.transport.KNNWarmupTransportActionTests.classMethod
 - com.amazon.opendistroforelasticsearch.knn.plugin.stats.KNNCounterTests.classMethod

11 tests completed, 11 failed
Finished generating test XML results (0.001 secs) into: /root/k-NN/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.003 secs) into: /root/k-NN/build/reports/tests/test
:test (Thread[Execution worker for ':',5,main]) completed. Took 5.585 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///root/k-NN/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
27 actionable tasks: 4 executed, 23 up-to-date
```

**Comment by hoangpmb** [comment]
You try cmd: ./gradlew build -x test -x integTestRunner -x jacocoTestReport
