### ISSUE TITLE
Rescore query

### ISSUE THREAD

**Issue by frederichaase** [opendistro-for-elasticsearch/k-NN#184]
Is the `rescore`query supported in opendistro? Can it be used in conjunction with k-NN retrieval? I first want to filter some documents, that are rescored afterwards based on a vector computation. Reason why i use rescore query is the `window_size` parameter, which allows to limit the expensive vector calculation to a limited subset of documents. 

The query in normal elasticsearch looks similar to this:

```json
"query": {
    "match_all": {}
     },
    "rescore": {
        "window_size": 10, 
        "query": {
            "rescore_query": {
                "script_score": {
                    "query": {
                        "match_all": {}},
                    "script": {
                        "source": ...,
                    }
                }
            }
      }
}
```

Is something similar possible in opendistro? Or more precise: are `knn` queries allowed to run in rescore queries?

**Comment by vamshin** [comment]
Hi @fhaase2,

We do not have this support and  we are actively working on this feature https://github.com/opendistro-for-elasticsearch/k-NN/issues/50.

As a Work around(closest work around i could think of) you may want to try out similar to below example but this would not achieve scoring only the filtered/subset of documents.  This would return the knn scores for the documents that are the closest to the query vector and match the criteria. Please note our k-NN search is pretty fast as the graphs are indexed and scores should be evaluated pretty fast, so this might not be a real issue but you might want to experiment on this.

```
POST index_name/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "function_score": {
            "query": {
              "knn": {
                  "my_vector": {
                  "vector": [6, 6],
                  "k": 4
                  }       
              }
          },
            "weight": 1 // this way all the score would be coming from the vector computation i.e k-NN score.
          }
        },
        {
          "function_score": {
            "query": {
              "match": {
                "abstract": "gilmour"
              }
            },
            "weight": 0
          }
        }
      ]
    }
  }
}
```

**Comment by addy336** [comment]
@vamshin I'm planning to use this plugin for my project. You mentioned that this is pretty fast. What kind of time would it take on a t2.xlarge (16gb ram) machine for a knn query on 100 million vectors of 100 dimensions?

**Comment by lexNeurii** [comment]
@vamshin I store a lot of 100 d vectors for each document, however, I feel that I can do all my calculations using this hash. These embedding vectors eat up a lot of space for me. Is it possible for me to index the vectors and then retain the hash representation only for calculations and remove the vectors so that I can save on space?
