### ISSUE TITLE
Does nmslib-hnsw index support "mmap" during inference time?

### ISSUE THREAD

**Issue by raman-r-4978** [opendistro-for-elasticsearch/k-NN#185]
Hi,

I have few doubts on "nmslib" part, would like to get some clarifications

1. Is there any way to speed up the index creation other than setting "threadQty" ?

2. Say If I want to load a large index (size=3G), are there any methods that could help me load the indexes efficiently? something like mmap?

**Comment by vamshin** [comment]
Hi @RamanRajarathinam,

``` Is there any way to speed up the index creation other than setting "threadQty" ?```
Yes, you could refer this doc https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/PerformanceTuning.md#indexing-performance-tuning

```2. Say If I want to load a large index (size=3G), are there any methods that could help me load the indexes efficiently? something like mmap?```
I dont think nmslib has it but in our k-NN plugin we MMAP the serialized graph using Lucene Directoy and these graphs are only loaded once and cached in memory for further queries
