### ISSUE TITLE
existsQuery knn vecter is not run！

### ISSUE THREAD

**Issue by whitezdm** [opendistro-for-elasticsearch/k-NN#197]
when i use existquery to query the field definition knn vector,it not work . the item has date ,but when existsquery not find

**Comment by vamshin** [comment]
Hi @whitezdm,

Could you share the example query?

**Comment by whitezdm** [comment]
> Hi @whitezdm,
> 
> Could you share the example query?

{
    "query": {
        "exists": {
          "field": "imageVector"
        }
    }
}
imageVector item is vecter item 。i want find this item is not null. i use exits query in es 7.8 ,but it not work。i not know why？thanks

**Comment by dnwarnock** [comment]
I've noticed the same thing. Outside the KNN query DSL the vector fields don't seem compatible with other ES query types.

**Comment by vamshin** [comment]
@whitezdm @dnwarnock we are considering this as a feature request and we would update the availability of this feature on this thread.

**Comment by whitezdm** [comment]
> @whitezdm @dnwarnock we are considering this as a feature request and we would update the availability of this feature on this thread.

very expect

**Comment by jmazanec15** [comment]
@dnwarnock @whitezdm are there other ES query types that would be useful for your use cases?

**Comment by whitezdm** [comment]
> @dnwarnock @whitezdm are there other ES query types that would be useful for your use cases?

other types can work very well.

**Comment by dnwarnock** [comment]
It would be nice to be able to query for documents that have non null vector fields to collect metrics around how many documents for a given index have associated embeddings. Also the ability to rerank based off some other document feature/metadata would be useful.

**Comment by hjander** [comment]
I am missing exactly this functionality. When will it be available in OpenDistro ? I am using AWS ES 7..7

**Comment by jmazanec15** [comment]
Hi @hjander 

In opendistro, this will be available in opendistro-1.11, which will be available in the next couple of weeks.

At the moment, it is not yet determined when this will be in Amazon Elasticsearch Service.

We will update this thread with more information.

**Comment by vamshin** [comment]
This is now available in Amazon Elasticsearch service from 7.9 onwards
