### ISSUE TITLE
Expose similarity score functions as part of custom scoring

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#213]
Expose functions that evaluate the similarity score like Euclidean, cosine etc so that users can perform their own scoring.

**Comment by vamshin** [comment]
https://discuss.opendistrocommunity.dev/t/combining-knn-score-with-keyword-query/3600/3

**Comment by ngadkari** [comment]
This will be a pretty useful feature for mixing knn and keyword search results. Is there an ETA for this feature

**Comment by timforr** [comment]
Any updates on if this will make it in to the next release?

**Comment by vamshin** [comment]
Hi @timforr, @VijayanB is working on the PR and we should be ready for odfe1.13 release. 

As a side note we already have custom scoring exposed from odfe 1.11  https://opendistro.github.io/for-elasticsearch-docs/docs/knn/#custom-scoring
