### ISSUE TITLE
Search score above 1.0

### ISSUE THREAD

**Issue by tanguilp** [opendistro-for-elasticsearch/k-NN#219]
Using the k-nn plugin, I frequently get results with score above zero, for instance:

```
{"took":2,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":60,"relation":"eq"},"max_score":1.0000002,...
```

This happens when the searched vector is the same as a vector already indexed.

Is it the expected behaviour?

**Comment by jmazanec15** [comment]
Hi @tanguilp 

I looked into this today. In nmslib, during distance calculation, some precision is lost during floating point calculations. This will cause the score to not be exactly 1.0. 

After some investigation, it looks like more precision is lost when using AVX instructions. [Here](https://github.com/nmslib/nmslib/blob/master/similarity_search/src/method/hnsw_distfunc_opt.cc#L194) is the code for distance computation for cosine similarity in nmslib. This should not impact the plugin's accuracy, except for some edge cases (i.e. a large set of vectors are very similar to each other).

Is this impacting your use case?

Jack

**Comment by tanguilp** [comment]
That's what I was suspecting, thanks for looking at it!

It's not impacting my use case, I can programmatically cap scores to 1. If this is not considered a bug, I think this issue can be closed.

**Comment by jmazanec15** [comment]
Sure, closing for now. If you run into an issue, please reopen.
