### ISSUE TITLE
Add README section for Custom scoring feature

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#222]
Add README section for Custom scoring feature 
Parent PR:- https://github.com/opendistro-for-elasticsearch/k-NN/pull/196

**Comment by jmazanec15** [comment]
Related PR: https://github.com/opendistro/for-elasticsearch-docs/pull/396

In order to standardize docs, we should host all usage information in the documentation located here: https://opendistro.github.io/for-elasticsearch-docs/docs/knn/
