### ISSUE TITLE
Support for Manhattan distance (L1)

### ISSUE THREAD

**Issue by elb3k** [opendistro-for-elasticsearch/k-NN#226]
As many usages of knn_vector search done in high dimensional space. From posts like curse of dimensionality suggests that L1 distance is better metric in high dimensional vectors. KNN vector type supports just L2 and Cosine similarity.

I am asking L1 feature request for ```knn.space_type```

**Comment by vamshin** [comment]
Hi @Elbek-Khoshimjonov. Would leave this thread as a feature request. Any one reaching this thread for ```L1``` feature please +1. This will help us prioritize the feature.
