### ISSUE TITLE
suggest is not a SuggestField

### ISSUE THREAD

**Issue by paintmeyellow** [opendistro-for-elasticsearch/k-NN#227]
Why when I am using `"index.knn = true"` I got error `suggest is not a SuggestField`?

Here is the **mapping** of suggest field:
```
"suggest": {
    "type": "completion",
    "analyzer": "simple",
    "preserve_separators": true,
    "preserve_position_increments": false,
    "max_input_length": 50
}
```
Here is the problem part of **query**:
```
"suggest": {
    "prefix_suggest": {
        "text": "white",
        "completion": {
            "field": "suggest"
        }
    }
}
```

**Comment by vamshin** [comment]
Hi @Nikitos096,

Could you please provide the complete index mapping and the query to reproduce at our end?

**Comment by paintmeyellow** [comment]
> Hi @Nikitos096,
> 
> Could you please provide the complete index mapping and the query to reproduce at our end?

Yep, here you go:
```
PUT music
{
  "settings": {
    "index": {
      "knn": true
    }
  }, 
  "mappings": {
    "properties": {
      "suggest": {
        "type": "completion"
      }
    }
  }
}

PUT music/_doc/1?refresh
{
  "suggest" : {
    "input": [ "Nevermind", "Nirvana" ],
    "weight" : 34
  }
}

POST music/_search?pretty
{
  "suggest": {
    "song-suggest": {
      "prefix": "nir",        
      "completion": {         
          "field": "suggest"  
      }
    }
  }
}
```
Source: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-suggesters.html#completion-suggester

**Comment by vamshin** [comment]
Looks like KNNCodec is missing this implementation. Will dig into this and update the thread soon.

**Comment by vamshin** [comment]
We are considering this as a bug and we would prioritize the fix accordingly.
