### ISSUE TITLE
Add binary Hamming distance to custom scoring

### ISSUE THREAD

**Issue by jmazanec15** [opendistro-for-elasticsearch/k-NN#264]
The Hamming distance measures the number of positions that are different between 2 equal length sequences of characters. This feature will look to support Hamming distance for binary sequences within the custom scoring logic.

A user should be able to ingest documents that have a term that can be interpreted as binary data and then apply the k-NN custom scoring script in order to get the k most similar results based on this distance metric. In order to implement this, we will need to determine which Elasticsearch types we will use to represent binary data. For instance, Elasticsearch has the [binary field type](https://www.elastic.co/guide/en/elasticsearch/reference/current/binary.html), that uses Base64 encoded values. We will also look into supporting integral types (long, int, short, byte) and their related arrays. These may offer performance improvements over Base64.

Additional enhancements to this feature include supporting fixed radius nearest neighbor search, which will return all documents that fall within a certain radius of the query data.

**Comment by luyuncheng** [comment]
i see there is [space_bit_hamming](https://github.com/nmslib/nmslib/blob/master/similarity_search/include/factory/space/space_bit_hamming.h) in nmslib. is there any possible use this space in k-NN?

**Comment by jmazanec15** [comment]
Hi @luyuncheng I think we could investigate adding that functionality. Because this issue is dedicated to adding Hamming distance in custom scoring, I am going to close it. Could you please open a separate issue for integrating nmslib's hamming bit space into the plugin?
