### ISSUE TITLE
Does the knn field support array values?

### ISSUE THREAD

**Issue by wrkaiser** [opendistro-for-elasticsearch/k-NN#266]
eg. 
{
    "my_vector1" : [[1.5, 2.5], [2, 3], [3.5, 5]],
    "price":10
}

**Comment by vamshin** [comment]
Hi @wrkaiser, at this point we do not support array values. You could add multiple fields in the index and add vectors in a single document. If you are looking into index into a single field, then every document should have one vector

**Comment by wrkaiser** [comment]
Thx~~  I considered that you said, but the number of value is not fixed.

**Comment by vamshin** [comment]
Sorry what do you mean by number of value is not fixed?

**Comment by wrkaiser** [comment]
The length of array no fixed. 

example,~
doc1:   {"my_vector1" : [[1.5, 2.5], [2, 3], [3.5, 5]]}
doc2:   {"my_vector1" : [ [2, 7], [3, 3]]}

**Comment by vamshin** [comment]
You will add one vector per document i.e each element of array which is a vector will be indexed in one document of Elasticsearch.  As the number of vectors increase documents would increase.

**Comment by wrkaiser** [comment]
thank you, i get~
