### ISSUE TITLE
Make Pre-Filtering (Custom Scoring) Faster

### ISSUE THREAD

**Issue by H-Shafiei** [opendistro-for-elasticsearch/k-NN#276]
Hi,

I want to use elastic search to perform a similarity search through my vectors (cosine similarity). I would like to have the search done in a subset of the documents.

I have seen that this can be done through custom scoring. The problem is the performance drop compared to the indexed knn. I guess it is due to the custom scoring is brute-forcing instead of searching through the hnsw indexed vectors.

Is there any way I can perform the prefilter search without a major performance drop?

Thanks

**Comment by H-Shafiei** [comment]
I have one thought for making it faster but I don't know how can I implement it:

We can index the normalized versions of the vectors and normalize the query before performing the search. This way for a normal search we won't lose performance and when we want to search with a custom scoring approach, we can search with just a dot product (as I am searching with cosine similarity space and it is same when the vectors are normalized) which is faster than cosine similarity.

If this is a good idea how can I implement it? And if it's not may I know why?

**Comment by jmazanec15** [comment]
HI @H-Shafiei 

Your approach would be faster. Basically, it would be the cosineOptimized function without these lines: [one](https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringUtil.java#L57), [two](https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringUtil.java#L59), and [three](https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNScoringUtil.java#L64). It would not be too difficult to create a dot product space for our custom scoring approach. We can treat this as a feature request.

That being said, performance would speed up, but a brute force search will take the same time complexity, regardless of space. What is your current latency with cosine approach and what is your target latency?

**Comment by vamshin** [comment]
Closing this thread as its one month older. Feel free to reopen incase of the issues.
