### ISSUE TITLE
help with warmup api

### ISSUE THREAD

**Issue by stephenleo** [opendistro-for-elasticsearch/k-NN#277]
Hi, I run the warmup API from Python using requests package and get the successful response

```
response = requests.get('https://localhost:9200/_opendistro/_knn/warmup/product-idx?pretty', auth=('admin', 'admin'), verify=False)
print(response.text)
```
```
{
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  }
}
```

However, the very first query I run still takes an abnormally long amount of time. Sorry if I'm doing something simple wrong, but any help to speed up the very first query is appreciated. If any other additional info will help troubleshoot pls let me know also. Thanks!

df is just a dataframe that looks like below
![image](https://user-images.githubusercontent.com/35026793/101603922-3add5f80-3a3b-11eb-95cc-3bb863ce4444.png)

```
# Check time for each query
for idx, row in enumerate(df.itertuples()):
    start = datetime.now()
    prod_payload = '{"size": 100, "query": {"knn": {"emb": {"vector":'+ str(getattr(row, "emb").tolist()) +',"k": 100}}}}'
    response = requests.post("https://localhost:9200/product-idx/_search", data=prod_payload, headers={'content-type': 'application/json'}, auth=('admin', 'admin'), verify=False) 
    end = datetime.now()
    print(f"Query time of {idx}th query : {(end-start).total_seconds() * 1000:.2f} milliseconds")
```

```
Query time of 0th query : 14978.69 milliseconds
Query time of 1th query : 57.96 milliseconds
Query time of 2th query : 57.30 milliseconds
Query time of 3th query : 56.60 milliseconds
Query time of 4th query : 69.25 milliseconds
Query time of 5th query : 59.41 milliseconds
```

Edit: the issue resolves itself if I wait for some time (say 5 minutes) after pushing in data and before running the warmup.

```
Query time of 0th query : 56.24 milliseconds
Query time of 1th query : 54.37 milliseconds
Query time of 2th query : 62.96 milliseconds
Query time of 3th query : 54.54 milliseconds
Query time of 4th query : 54.93 milliseconds
```

**Comment by jmazanec15** [comment]
@stephenleo Makes sense. I think after indexing data, you can execute a refresh operation on the index to make the data searchable and then run warmup API.

**Comment by stephenleo** [comment]
Thank you! Yes, I added a refresh with sufficient timeout before the warmup API and it works fine now.
