### ISSUE TITLE
Support cosine similarity[Experimental]

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#28]
This sim is to help prioritize the cosine similarity feature. Please +1 if you end up here :)

**Comment by mickdelaney** [comment]
We would be huge fans of this also. We currently do this out of ES

**Comment by vamshin** [comment]
Merged to 1.7 release. Should be available part of 1.7 docker images.
We are marking this feature experimental as we are still evaluating the performance.

We will update this thread once we have done evaluation. Thank you
