### ISSUE TITLE
Elasticsearch crashes when using KNN fields

### ISSUE THREAD

**Issue by adrianpaiva1** [opendistro-for-elasticsearch/k-NN#296]
`A fatal error has been detected by the Java Runtime Environment:
elasticsearch    | #
elasticsearch    | #  SIGILL (0x4) at pc=0x00007fb5c03e7f89, pid=1, tid=281
elasticsearch    | #
elasticsearch    | # JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.1+7) (build 14.0.1+7)
elasticsearch    | # Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.1+7, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
elasticsearch    | # Problematic frame:
elasticsearch    | # C  [libKNNIndexV1_7_3_6.so+0x1a1f89]  float std::generate_canonical<float, 24ul, std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> >(std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>&)+0x1c9`

When indexing vectors (768 dimensions) into a knn vector field ES crashes over and over.

This happens on both version 1.9 & 1.8 using docker. After it crashes on the first index, I have to actually remove the docker volume for the ES container to start without throwing this error.

column mapping setting

`"vector" => [
                        "type" => "knn_vector",
                        "dimension" => 768,
                    ],`

index settings

`'knn' => true,
 'knn.space_type' => 'cosinesimil'`

**Comment by vamshin** [comment]
This is being addressed in k-nn forum https://discuss.opendistrocommunity.dev/t/es-crashes-when-indexing-knn-vectors/3682. 

@adrianpaiva1 Are you still facing the issue?
