### ISSUE TITLE
Inconsistent results for approximate knn search

### ISSUE THREAD

**Issue by sujithjoseph** [opendistro-for-elasticsearch/k-NN#298]
When I perform a query with a post filter to check for a specific results, I get inconsistent results. ie. 8 out of 10 tries only provides a result back (testing from Kibana).  

```
"query" : {
      "bool" : {
        "filter" : {
          "terms" : {
            "id" : [
              "12345"
            ]
          }
        },
        "must" : {
          "knn" : {
            "doc" : {
              "k" : 10000,
              "vector" : [
                0.027234218608544556,
                -0.0014569142062703807....
```
I get 0 results at random
```
{
  "took" : 53,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
} ```

**Comment by sujithjoseph** [comment]
Using 1.10.1.0 knn version. What could possibly cause this behavior? It is searching about 2-3M vectors with k as 10K.

**Comment by vamshin** [comment]
Hi @sujithjoseph,

When you run just the knn query with k=10000 multiple times, do you always get the results? Just trying to check if its something with knn query or post filter approach.

By the way starting 1.11.0.0, we have support for custom scoring where you will have ability to apply knn search dynamically on the filtered set of documents(i.e applying knn on post filtered documents). https://opendistro.github.io/for-elasticsearch-docs/docs/knn/#pre-filtering-with-custom-scoring

**Comment by sujithjoseph** [comment]
@vamshin Yes, we always get results if I dont pass the post filter. Is the post filter happening at shard level or segment level? Or does it happen at coordinator node level? for 1.11 , is it a greedy match or approximate knn , as we have more than 20K docs (close to millions).  If I increase M factor to say 48, for heavy load indexing of a 200 dimension vector Elastic becomes un-responsive for a batch size of 50 docs and 4 workers (logstash). Scaling it down to default of 16 worked well.

**Comment by sujithjoseph** [comment]
Will also upgrade to 1.10.x and see if this problem can be replicated. I have 2 Elastic environments with the same index. In one environment i see this inconsistent results, but in the other, It is consistent, but i see 0 results all the time. I did warm up the index in both the environments. With this custom scoring in  1.11.0.0 and  1.10.x, i am assuming we can use it for re-ranking results using knn match on embeddings just for top 50 results from Elastic. https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-rescore.html .  
```
POST /_search
{
   "query" : {
      "match" : {
         "message" : {
            "operator" : "or",
            "query" : "the quick brown"
         }
      }
   },
   "rescore" : {
      "window_size" : 50,
      "query" : {
         "rescore_query" : {

  function_score" : {
      "script_score": {
     "query": {
       "match_all": {}
     },
     "script": {
       "source": "knn_score",
       "lang": "knn",
       "params": {
         "field": "my_vector2",
         "query_value": [2, 3, 5, 6],
         "space_type": "cosinesimil"
       }
     }
   }
}
         },
         "query_weight" : 0.7,
         "rescore_query_weight" : 1.2
      }
   }
}```

**Comment by sujithjoseph** [comment]
@vamshin , should i set knn.algo_param.ef_search" same as K value,  if K is high like 10K?

**Comment by vamshin** [comment]
> @vamshin Yes, we always get results if I dont pass the post filter. Is the post filter happening at shard level or segment level? Or does it happen at coordinator node level? 

My understanding this should happen at coordinate level.

>for 1.11 , is it a greedy match or approximate knn , as we have more than 20K docs (close to millions). 
  
This is greedy match but works well if your use cases is to apply knn dynamically on smaller subset of the docs. This greedy approach would give recall 1. To minimize the latencies, you could spread the documents across multiple shards. This way the greedy search can happen parallel. Please note you can avoid ```index.knn=true``` if you plan to just do greedy search.

>If I increase M factor to say 48, for heavy load indexing of a 200 dimension vector Elastic becomes un-responsive for a batch size of 50 docs and 4 workers (logstash). Scaling it down to default of 16 worked well.

This is expected. The more the M the more number of bidirectional links and more memory would require. You may have to choose better instance type with more RAM to support your use case or spread the shards across multiple nodes.

**Comment by vamshin** [comment]
> Will also upgrade to 1.10.x and see if this problem can be replicated. I have 2 Elastic environments with the same index. In one environment i see this inconsistent results, but in the other, It is consistent, but i see 0 results all the time. I did warm up the index in both the environments. With this custom scoring in 1.11.0.0 and 1.10.x, i am assuming we can use it for re-ranking results using knn match on embeddings just for top 50 results from Elastic. https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-rescore.html .

Custom scoring implicitly does rescoring. You do not have to call rescore again. Custom scoring basically replaces the score of the filtered docs with the knn score.  You could refer the custom scoring example in this doc https://opendistro.github.io/for-elasticsearch-docs/docs/knn/

**Comment by sujithjoseph** [comment]
Thanks @vamshin. The advantage with rescoring is that it just need to work on fewer set of docs say 50 - 200 results from original query, like 'Learn to Rank' models, which would be very fast. I am assuming rescoring will work as well with custom script function.

**Comment by vamshin** [comment]
> Thanks @vamshin. The advantage with rescoring is that it just need to work on fewer set of docs say 50 - 200 results from original query, like 'Learn to Rank' models, which would be very fast. I am assuming rescoring will work as well with custom script function.

@sujithjoseph got it. The difference I could notice between ```rescore``` and  ```Custom scoring``` is rescore just applies to the filtered docs at the shard level where as  custom scoring applies to the  filtered documents at segment level from original query in the shard. From this observation,  you are right. Rescore query should be faster than custom scoring.  Good to know. Thanks.
