### ISSUE TITLE
Script to build the nmslib and drop in the java library path.

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#30]
nmslib C library should be build locally to the host machine to avoid compatibility issues with respect to cpu optimization instructions, c compiler etc. 

We need to have a script that can build the library local to the host machine to support development/usage of knn plugin for various plugin distributions like deb, tar, zip etc

**Comment by jmazanec15** [comment]
Addressed by #83. Closing issue
