### ISSUE TITLE
How much memory occupied if index of  hnsw  file all loaded into memory?

### ISSUE THREAD

**Issue by wrkaiser** [opendistro-for-elasticsearch/k-NN#300]
Hi，
    My index  has merged one segment in one shard, and ".hnsw" file size is 2.1g，i want to know  whether has  statistics that are completely loaded into memory?

thanks.

**Comment by wrkaiser** [comment]
when i use warm up api , the error message is as follows:
![image](https://user-images.githubusercontent.com/11936352/104164917-9da78980-5433-11eb-829f-04d78ca40da4.png)

**Comment by jmazanec15** [comment]
Hi @wrkaiser 

`/_opendistro/_stats` will tell you what has been loaded into memory.

The failure for the warmup API is strange. Could you provide the following information?
1. ODFE version number
2. ODFE artifact type (Docker, RPM, TAR, etc)

Additionally, could you run the command:
`/_cat/plugins` and paste the output?

**Comment by wrkaiser** [comment]
thanks，i get.

I should be using the oldest version that is 1.4.0.0.

**Comment by wrkaiser** [comment]
hi，
     Does the release version not provide packages that can be used directly?
![QQ截图20210113165932](https://user-images.githubusercontent.com/11936352/104429702-e3458d00-55c0-11eb-9841-60ea494c8102.png)

**Comment by wrkaiser** [comment]
hi @jmazanec15,
        Coulde provide can directly used package in the lastest version?

thanks.

**Comment by wrkaiser** [comment]
hi，@vamshin,
     My network has wall，download dependent package is so slowly.  I'm very much hope that you can provide a package that can be used directly.

thanks.

**Comment by jmazanec15** [comment]
Hi @wrkaiser ,

Apologies, are you using ODFE 1.4?

**Comment by wrkaiser** [comment]
hi @jmazanec15,

   Yes, i plan to upgrade to the latest version.

**Comment by jmazanec15** [comment]
Oh okay thanks @wrkaiser. So which packages do you need? opendistro-knn-1.12.0.0.zip and libKNNIndexV206.so?

**Comment by wrkaiser** [comment]
@jmazanec15， yes~!

**Comment by jmazanec15** [comment]
You should be able to get them from the tar ball: https://opendistro.github.io/for-elasticsearch-docs/docs/install/tar/

```
curl https://d3g5vo6xdbdb9a.cloudfront.net/tarball/opendistro-elasticsearch/opendistroforelasticsearch-1.12.0.tar.gz -o opendistroforelasticsearch-1.12.0.tar.gz

cd plugins/opendistro-knn/

ls
ls knn-lib
```
Please let me know if that does not work.
