### ISSUE TITLE
Docker image including k-NN plugin

### ISSUE THREAD

**Issue by da2r-20** [opendistro-for-elasticsearch/k-NN#31]
I've pulled amazon/opendistro-for-elasticsearch
but it doesn't contain the knn plugin.

```
$ docker run --rm -it --name es-knn amazon/opendistro-for-elasticsearch bash
$ ll plugins
drwxrwxr-x 2 elasticsearch root 4096 Dec 11 09:33 opendistro-job-scheduler
drwxrwxr-x 2 elasticsearch root 4096 Dec 11 09:33 opendistro_alerting
drwxrwxr-x 2 elasticsearch root 4096 Dec 11 09:34 opendistro_index_management
drwxrwxr-x 5 elasticsearch root 4096 Dec 11 09:34 opendistro_performance_analyzer
drwxrwxr-x 4 elasticsearch root 4096 Dec 11 09:34 opendistro_security
drwxrwxr-x 2 elasticsearch root 4096 Dec 11 09:33 opendistro_sql
```

There is an in-official image that includes knn
ferdous/odfes_elasticsearch_knn

Can we have this plugin included in the official docker image?

**Comment by vamshin** [comment]
Hi @doronAtuar ,

Thanks for your interest in k-NN plugin.

You are right. We have not build the knn plugin in docker image.  We are working on including it in the 1.4  opendistro docker release which is expected to release very soon. stay tuned :)

**Comment by vamshin** [comment]
Hi @doronAtuar,

Ongoing PR https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/74 for knn support in docker image.
