### ISSUE TITLE
Number of results far less than k or size

### ISSUE THREAD

**Issue by smodlich** [opendistro-for-elasticsearch/k-NN#333]
Hi,

I've been trying out the KNN component recently. I've stumbled upon a problem with the number of search results. I'm running a search for an approximate KNN index with 4 million documents asking for 10.000 results. Everything is merged in one segment. After indexing I run refresh and warmup API's. Also I changed back refresh_interval to 1s. Vector dimension is 100 and query as well. Vectors come from PCA and are originally from NLP domain.

However I always get far less than 10000 results? Also it varies by query? Sometimes I get only 500 results sometimes 3000? How is this possible? I checked and the index contains many more documents. Response times are ok and RAM is sufficent for graph size from my checks. I expected k+size to be lower threshold for number of results?

Search:
```
{
  "size": 10000,
  "query": {
    "knn": {
      "sem_vector": {
        "vector": query_vec,
        "k": 10000
      }
    }
  }
}
```

Index creation:
```
{
  "settings": {
    "index": {
      "knn": true,
      "knn.space_type": "cosinesimil",
      "refresh_interval":"-1",
      "number_of_replicas": 0
    }
  },
  "mappings": {
    "properties": {
      "sem_vector": {
        "type": "knn_vector",
        "dimension": 100
      },
    "other_fields":"..."
    }
  }
}
```

Thanks for any help

**Comment by vamshin** [comment]
Hi @smodlich,

What is the odfe version against which you faced this issue?

**Comment by smodlich** [comment]
Hi @vamshin , I'm using odes 1.12.0 with ES 7.10.0. Since I wrote this issue I removed duplicate texts from my index. This seems to have helped, now I'm getting 4500-7500 results when entering k + size as 10000. Can this happen because of the data/graph structure? I may still have a lot of "almost" duplicates in my text data which will result in very close vectors. Could this cause issues with disconnected graph parts?

**Comment by vamshin** [comment]
@smodlich Correct. Duplicate vectors could be the issue. If this is for experimentation, you could try standard data sets like glove or sift.

Could you increase the hyper parameters and see if we get better results. I am assuming you are using defaults.
How about we make m=48, efconstruction=1024, efSearch=1024?

You can refer this doc for modifying settings https://opendistro.github.io/for-elasticsearch-docs/docs/knn/settings/#index-settings

**Comment by smodlich** [comment]
Hi @vamshin I finally came around trying the suggested parameters. It works, I'm now getting 10k results as expected. So this can be closed. Would maybe be good to add a hint to documentation that these parameters influence results numbers sometimes?
