### ISSUE TITLE
K-nn prefilter reports missing query vector paramater using docker v 1.11.0 or AWS 7.9

### ISSUE THREAD

**Issue by mikesaclgithubaccount** [opendistro-for-elasticsearch/k-NN#336]
When running elasticsearch locally using the `1.11.0` tagged image, or the AWS managed version, I am not able to perform K-NN search using prefilters.

Reproduction steps:

1. Run elasticsearch opendistro via:
`docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" amazon/opendistro-for-elasticsearch:1.11.0`
2. Create an index as outlined in the following image, which is basically the same as the example from the docs: 
![image](https://user-images.githubusercontent.com/46539693/110019385-3db7bb80-7cdd-11eb-9a81-90b167dd1a67.png)
3. Populate the index as per the docs: 
![image](https://user-images.githubusercontent.com/46539693/110019455-5627d600-7cdd-11eb-9a5b-bdf199776d09.png)
4. Attempt to query using a term prefilter, note error:
![image](https://user-images.githubusercontent.com/46539693/110019529-6f308700-7cdd-11eb-8680-1ab6fb55b0e4.png)

Expected behaviour:
Results returned with only color set to `2`.

Note that this query executes as expected in versions >= `1.12.0`

**Comment by vamshin** [comment]
Hi @mikesaclgithubaccount ,

In odfe 1.11.0.0, the param name is "[vector](https://github.com/opendistro-for-elasticsearch/k-NN/blob/73f75576101cae8e2d50f4ee3895d3685d5dc28e/src/main/java/com/amazon/opendistroforelasticsearch/knn/plugin/script/KNNVectorScoreScript.java#L142)", this is replaced to "query_value" in later versions.

Sorry for inconvenience.

**Comment by mikesaclgithubaccount** [comment]
Thanks a lot @vamshin! I noticed that the docs aren't clearly versioned. Would you be able to point me towards the docs/api reference for odfe 1.11.0.0?

**Comment by vamshin** [comment]
Hi @mikesaclgithubaccount, please find documentation here https://opendistro.github.io/for-elasticsearch-docs/old/1.11.0/docs/knn/#custom-scoring
