### ISSUE TITLE
Error while installing elasticsearch onto my ubuntu 20.4 version

### ISSUE THREAD

**Issue by yashi0099** [opendistro-for-elasticsearch/k-NN#346]
root@yshicoder:/home/yshicoder/Desktop# sudo apt-get install elasticsearch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package elasticsearch

#131

**Comment by VijayanB** [comment]
Can you try the instructions that are mentioned here?
https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/
