### ISSUE TITLE
Whether the vector cache memory supports sharding

### ISSUE THREAD

**Issue by LinXiaoJian** [opendistro-for-elasticsearch/k-NN#349]
We currently have 10,000 pieces of 768 dimensions of data that need to be stored every day.
If each data node loaded all vector data into memory, it would take up a lot of memory.
I would like to know if the vector cache memory can be spread across different machines to support horizontal scaling
Looking forward to your reply. Thank you

**Comment by jmazanec15** [comment]
Closing. Continuing discussion here: https://discuss.opendistrocommunity.dev/t/whether-the-vector-cache-memory-supports-sharding/6220/5
