### ISSUE TITLE
Memory for exact search only

### ISSUE THREAD

**Issue by jaredsohn** [opendistro-for-elasticsearch/k-NN#354]
I see memory requirements for approximate knn at https://opendistro.github.io/for-elasticsearch-docs/docs/knn/approximate-knn/.

Is there a way to use knn for exact search only and avoid those memory requirements? Since it looks like memory structures are populated upon first use do I just need to create an index and never use it with an approximate query?

**Comment by VijayanB** [comment]
@jaredsohn Those memory requirements are for knn index . In your scenario, you can create an index without following setting `knn: true` and use it for exact search. This will not create any knn specific files, hence those memory requirements will not be applicable to this index. You can read more about this [here](https://opendistro.github.io/for-elasticsearch-docs/docs/knn/knn-score-script/#getting-started-with-the-score-script-for-vectors)
