### ISSUE TITLE
this request accesses system indices

### ISSUE THREAD

**Issue by snthibaud** [opendistro-for-elasticsearch/k-NN#356]
Hello! I am a happy KNN-plugin user, but wanted to report this warning. A similar message appears on every KNN-search request to ElasticSearch for me. Can it be disabled? I do not think I accessed these system indices myself. Does the plugin access system indices internally?

odfe-node1   | [2021-07-27T00:57:23,558][DEPRECATION][o.e.d.c.m.IndexNameExpressionResolver] [odfe-node1] this request accesses system indices: [.kibana_1, .kibana_92668751_admin_1], but in a future major version, direct access to system indices will be prevented by default

**Comment by vamshin** [comment]
Hi @snthibaud, no k-NN plugin does not access any system indices. Could be part of security plugin running on your cluster?

There is a dedicated GitHub issues about this deprecation warning spamming the logs https://github.com/opensearch-project/security/issues/1307#issuecomment-887791155. Please feel free to comment on the GitHub issue as well

**Comment by snthibaud** [comment]
@vamshin Thank you. I am now following that issue!
