### ISSUE TITLE
.so library compatibility issue

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#4]
Hi @antonisloizou ,

From initial observation, looks like compatibility issue of .so lib. Can you help us understand, the environment where you are installing the plugin like os, cpu family etc.  Creating an issue to follow up more on this on a different thread

**Comment by antonisloizou** [comment]
Hi - thanks for the quick response!

OS: Ubuntu 18.04
JDK: OpenJDK 12.0.2+10
CPU: AMD Phenom II X6 1090T

**Comment by vamshin** [comment]
Hi @antonisloizou ,

Apologies for the delay. This seems to be compatibility issue. Can we try to build ```libKNNIndexV1_7_3_6.so``` locally

Instructions to build ```.so``` locally :-

1. Make sure you have cmake and gcc installed.
`
sudo yum install cmake
`
`
sudo yum install gcc72-c++.x86_64
`

2. Check out NMS library to ```/tmp/nms```  and generate artifacts

```
cd /tmp/nms/
git clone https://github.com/nmslib/nmslib.git
cd nmslib
git checkout tags/v1.7.3.6
cd similarity_search
cmake .
make
```

3. Copy the .cpp and header files [here](https://github.com/opendistro-for-elasticsearch/k-NN/tree/V1.2.0.0-alpha.1/jni/src/v1736) to a folder /tmp/jni/

4. Generate the .so library 
```
cd /tmp/jni/

g++ -fPIC -I"<path to jdk>/include" -I"/<path to jdk>/include/linux" -I/tmp/nms/nmslib/similarity_search/include -std=c++11 -shared -o libKNNIndexV1_7_3_6.so org_elasticsearch_index_knn_v1736_KNNIndex.cpp -lNonMetricSpaceLib -L/tmp/nms/nmslib/similarity_search/release 

Example:-
g++ -fPIC -I"/home/vamshi/jdk1.8/include" -I"/home/vamshi/jdk1.8/include/linux" -I/home/vamshin/nmslib/nmslib/similarity_search/include -std=c++11 -shared -o libKNNIndexV1_7_3_6.so org_elasticsearch_index_knn_v1736_KNNIndex.cpp -lNonMetricSpaceLib -L/home/vamshin/nmslib/nmslib/similarity_search/release 
```

5. Checkout K-NN package to /tmp/knn/
```
cd /tmp/knn/
git clone https://github.com/opendistro-for-elasticsearch/k-NN.git
cd k-NN/
git checkout tags/V1.2.0.0-alpha.1
```

6. Replace the .so generated in ```/tmp/jni/``` with  [KNN .so](https://github.com/opendistro-for-elasticsearch/k-NN/blob/V1.2.0.0-alpha.1/buildSrc/libKNNIndexV1_7_3_6.so) 
```
mv /tmp/jni/libKNNIndexV1_7_3_6.so /tmp/k-NN/buildSrc/
```

7. Build the KNN library
```
cd /tmp/k-NN/
./gradlew build -x :integTestRunner -x :dumpCoverage -x :jacocoTestReport
```

8. Plugin zip would be generated in folder 
/tmp/k-NN/build/distributions/opendistro-knn-1.1.0.0.zip

We would create a script to do the above steps, to simplify the process of building ```.so``` soon.

**Comment by antonisloizou** [comment]
Thanks a lot! I've been able to build the .so and get the plugin running both on my local Ubuntu 18.04, but also for the Centos7 (glibc-2.17) based elasticsearch docker image.

Still, having a script to do this automatically would be great.

**Comment by spoonnotfound** [comment]
> I changed the gcc version and solved the problem.

I followed your instructions but still got wrong. The size of .so I compiled is 5.2MB, and I encounter the similar problem with @antonisloizou.
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007fc92767ecf0, pid=1, tid=147
#
# JRE version: OpenJDK Runtime Environment (12.0.2+10) (build 12.0.2+10)
# Java VM: OpenJDK 64-Bit Server VM (12.0.2+10, mixed mode, sharing, tiered, compressed oops, concurrent mark sweep gc, linux-amd64)
# Problematic frame:
# C  [libKNNIndexV1_7_3_6.so+0x16ecf0]  similarity::Hnsw<float>::CreateIndex(similarity::AnyParams const&)+0x630
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# Can not save log file, dump to screen..
```

**Comment by hahamark1** [comment]
While installing the plugin I get the following error:
`ERROR: Unknown plugin /homedir/romme/opendistro/k-NN/build/distributions/opendistro-knn-1.1.0.0.zip
`

I have the feeling that the zipfile is not complete, the only contents are:
```
plugin-descriptor.properties
plugin-security.policy
opendistro-knn-1.1.0.0.jar
```
Is this correct, or is there another reason opendistroforelasticsearch doesn't accept the plugin?

**Comment by vamshin** [comment]
@hahamark1 ,

Artifacts you are referring to seem to be correct.

You may want to use the latest opendistro release https://github.com/opendistro-for-elasticsearch/k-NN/releases/tag/v1.4.0.0 which uses Elasticsearch version 7.4.2 

Also let us know the installation procedure you are following?

**Comment by wmlc** [comment]
hi,
   I'm confused about how i use this plugin?
   Did i need installing this plugin  manually  into the opendistro-for-elasticsearch project?

**Comment by vamshin** [comment]
Hi @wmlc ,

How are planning to  run opendistro cluster? If you are using Docker 1.4 version, k-NN  plugin would come installed.  You do not have to run any manual steps

**Comment by jmazanec15** [comment]
Seems that recent questions on this issue are not directly related to the topic. Closing.
