### ISSUE TITLE
Support custom scoring function for vectors. Using k-NN scores in a script_score query

### ISSUE THREAD

**Issue by mikepalei** [opendistro-for-elasticsearch/k-NN#50]
Hi guys, is it possible to use your plugin in a script_score query (like below). If it is, could you please provide an example?

```
GET my_index/_search
{
  "query": {
    "script_score": {
      "query" : {
        "bool" : {
          "filter" : {
            "term" : {
              "status" : "published" 
            }
          }
        }
      },
      "script": {
        "source": "cosineSimilarity(params.query_vector, 'my_dense_vector') + 1.0", 
        "params": {
          "query_vector": [4, 3.4, -0.2]  
        }
      }
    }
  }
}
```

**Comment by vamshin** [comment]
Hi @mikepalei ,

We do not have support for painless query.

**Comment by mikepalei** [comment]
So there is no way to run your plugin against a limited set of vectors and not on the entire index?

**Comment by vamshin** [comment]
Hi @mikepalei,

Correct. At this point we do not have a way to run dynamically on the limited set of vectors.
Tagging this issue as Feature request. Feel free to +1.

**Comment by dwang-sflscientific** [comment]
I saw the PR is merged. Is the feature ready to use?

**Comment by vamshin** [comment]
Hi @dwang-sflscientific, this feature would be available in the next release i.e ODFE 1.11.
