### ISSUE TITLE
Execution failed for task ':integTestCluster#wait'.

### ISSUE THREAD

**Issue by wrkaiser** [opendistro-for-elasticsearch/k-NN#55]
hi,
    My os is windows 10,and already download and start the odfe service. But when i run "gradle build", one error occured as follow picture.

thanks.
![QQ截图20200224165716](https://user-images.githubusercontent.com/11936352/75139223-0bb56600-5727-11ea-9c4e-e336edbdc369.png)

**Comment by vamshin** [comment]
Hi @wrkaiser ,

Are you running odfe docker image?

You might want to try couple of things for above issue,

Remove build directory if already present. You would find this in k-NN plugin directory

```
 rm -rf build   
```

Kill Orphan elasticsearch process if any 
```
 ps -ax | grep elastic  
kill -9 <process_id_from_above_command>
```

Run clean
```
./gradlew clean
```

Run build
```
./gradlew build
```

**Comment by wrkaiser** [comment]
Thank you for your reply.

I not use  docker image.  i just want to use  K-NN plugin only in my ES cluster. 

Is build this k-NN project not depend on the running elastic service?

**Comment by wrkaiser** [comment]
Hi, 
   when the elastic service not running, and i run the gradle task of build in intellij idea.  

   Also has a another error as  follow picture. But i find  'opendistro-knn-1.4.0.jar' in build directory. 
![image](https://user-images.githubusercontent.com/11936352/75504056-562e2f80-5a12-11ea-81d6-5f0644d6a4bf.png)

  Want to ask if I still need to consider this error?

thanks.

**Comment by vamshin** [comment]
Hi @wrkaiser,

This seem to  be because of orphan process. Did you run the steps as suggested above?

As of today, we do not have NMS library build for windows. So running plugin on windows might not work. We will keep you posted on our support for k-NN for Windows
