### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by m0baxter** [opendistro-for-elasticsearch/k-NN#70]
Your documentation makes it clear the the current version is compatible with Elasticsearch 7.4.2 but I was wondering if it is backwards compatible? For example could I use this plugin in Elasticsearch 5.6?

**Comment by vamshin** [comment]
Hi @m0baxter ,

Sorry we do not have plugin support for Elasticsearch Version 5.6. As of today, we have support for Elasticsearch versions 7.2, 7.3, 7.4.  We do not have plan to support older versions.

**Comment by m0baxter** [comment]
Thanks, I was mostly curious.
