### ISSUE TITLE
OpenJDK download never ends

### ISSUE THREAD

**Issue by yinrong** [opendistro-for-elasticsearch/k-NN#93]
download too slow. Internet connection certainly fails after tens of minutes.

I successfully downloaded with pwget, any method to use my local file?

![image](https://user-images.githubusercontent.com/4221569/79336703-c4916780-7f56-11ea-8a6f-b5313737e803.png)

**Comment by vamshin** [comment]
Hi @yinrong,

Did you try ```./gradlew build```? Let us know if you still see the issue. This seems to be more of network problem.

**Comment by vamshin** [comment]
Closing the issue as no response on the thread. Feel free to reopen.
