### ISSUE TITLE
Block index writes to knn indices when the circuit breaker trips

### ISSUE THREAD

**Issue by vamshin** [opendistro-for-elasticsearch/k-NN#96]
As of today we do not block index writes to knn indices when graph memory circuit breaker triggers. We evict the entries in the cache to make room for new graphs.  One can keep adding more indices and result in the thrashing of cache which can degrade performance. We need to block the new index writes so that the performance does not degrade.

**Comment by chenqi0805** [comment]
@vamshin Have taken a look at the issue and will work on it if there is no duplicate effort. My plan is to add a `KNNSettings.isCircuitBreakerTriggered()` check in `addKNNBinaryField`. Let me know if this sounds reasonable. 

By reading the design doc, the only other module I can think of adding this logic is `IndexWriter`. But then we need to inherit and override its api.

**Comment by vamshin** [comment]
@chenqi0805 thanks for digging into the issue. You should be good to take this one.

We may need to reject the indexing requests at much earlier stages.  We could reject them even before parsing here https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/knn/index/KNNVectorFieldMapper.java#L239.
